[platformio]
default_envs = cyd_2432s032c

[env]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv
lib_deps =
  moononournation/GFX Library for Arduino@1.6.0
  bblanchon/ArduinoJson@7.2.1
  bblanchon/StreamUtils@1.9.0
  knolleary/PubSubClient@2.8.0
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#d57f64c8b5f2bc5b8d10d121550806eeff7b06d9

[env:cyd_2432s032r]
build_flags = -DCYD_TOUCH_RESISTIVE=1

[env:cyd_2432s032c]
build_flags = -DCYD_TOUCH_CAPACITIVE=1
